import "./theme-config.css";
import '@radix-ui/themes/styles.css';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryClientProviders from "@/QueryClientProviders";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import StyledComponentsRegistry from "@/app/registry";
import NavBar from './NabBar';
import { Container, Theme, ThemePanel } from '@radix-ui/themes';
import { SessionProvider } from "next-auth/react";
import AuthProvider from "./auth/Provider";

const inter = Inter({ 
  subsets: ["latin"],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Agence de location véhicule",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    

    <html lang="en" >
      <body className={inter.variable}>
      <AuthProvider>
        <QueryClientProviders>
            <Theme accentColor="violet">
                <NavBar />
                <main className="p-5"  
              /*  style={{
            backgroundImage: "url('/car1.jpg')",
            backdropFilter: "blur(10px)"
            
          }} */
          >
                  <Container>
                    <StyledComponentsRegistry>
                      {children}
                    </StyledComponentsRegistry>
                    </Container>
                </main>
                {/*<ThemePanel/>  */}
              </Theme>
            <ReactQueryDevtools initialIsOpen={false}/>
        </QueryClientProviders>
      </AuthProvider>
      </body>
    </html>
  );
}
       
